service: peanuts-comic-api

plugins:
  - serverless-domain-manager
  - serverless-bundle
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  customDomain:
    domainName: api.peanuts.today
    certificateName: '*.peanuts.today'
    basePath: ${self:custom.stage}
    stage: ${self:custom.stage}
    createRoute53Record: true
  bundle:
    sourcemaps: true
    caching: true
    stats: false
    linting: true
  existingResources:
    peanutsDynamoDBTable: peanuts-comics
    peanutsDynamoDBTableDateGSI: display_date-index

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: staging # default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt: [ subscribersTable, Arn ]
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/"
            - ${self:custom.existingResources.peanutsDynamoDBTable}*
  apiKeys:
    - ${self:custom.stage}-website

functions:
  api:
    handler: src/api.handler
    events:
      - http: 
          path: /
          method: any
          private: true
      - http: 
          path: '{proxy+}'
          method: any
          private: true
    environment:
      STAGE: ${self:custom.stage}
      peanutsDDBTable: ${self:custom.existingResources.peanutsDynamoDBTable}
      peanutsDDBTableDateGSI: ${self:custom.existingResources.peanutsDynamoDBTableDateGSI}
      peanutsSubscribersDDBTable: ${self:resources.Resources.subscribersTable.Properties.TableName}

resources:
  Resources:
    subscribersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: peanuts-comic-subscribers
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST